<?php

namespace DoctrineProxies\__CG__\Realms;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Player extends \Realms\Player implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPlayerId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["playerId"];
        }
        $this->__load();
        return parent::getPlayerId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getSessionId()
    {
        $this->__load();
        return parent::getSessionId();
    }

    public function setSessionId($sessionId)
    {
        $this->__load();
        return parent::setSessionId($sessionId);
    }

    public function getServers()
    {
        $this->__load();
        return parent::getServers();
    }

    public function getInvitations()
    {
        $this->__load();
        return parent::getInvitations();
    }

    public function getServer()
    {
        $this->__load();
        return parent::getServer();
    }

    public function setServer($server)
    {
        $this->__load();
        return parent::setServer($server);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'playerId', 'name', 'sessionId', 'servers', 'invitations', 'server');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}